/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import physiotherapy.sports.injury.centre.psic.Patient;
import physiotherapy.sports.injury.centre.psic.Physician;

/**
 *
 * @author Mubeen Khan
 */
public class AdminView extends javax.swing.JFrame {

    /**
     * Creates new form AdminView
     */
    public AdminView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelAdmin = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        panelAddPhysician = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelExpertise = new javax.swing.JScrollPane();
        listExpertise = new javax.swing.JList<>();
        txtFullName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        panelDaysWorking = new javax.swing.JScrollPane();
        listDaysWorking = new javax.swing.JList<>();
        txtConsultation = new javax.swing.JTextField();
        btnAddPhysician = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panelAddPatient = new javax.swing.JPanel();
        txtFullNamePatient = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAddressPatient = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPhonePatient = new javax.swing.JTextField();
        btnAddPatient = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Add Physician");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add Patient");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAdminLayout = new javax.swing.GroupLayout(panelAdmin);
        panelAdmin.setLayout(panelAdminLayout);
        panelAdminLayout.setHorizontalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        panelAdminLayout.setVerticalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", panelAdmin);

        jLabel1.setText("Full Name");

        jLabel2.setText("Address");

        jLabel3.setText("Phone No.");

        jLabel4.setText("Consultation Time");

        jLabel5.setText("Expertise");

        listExpertise.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Rehabilitation", "Physiotherapy", "Osteopathy" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        panelExpertise.setViewportView(listExpertise);

        jLabel6.setText("Day");

        listDaysWorking.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "05-04-2021", "06-04-2021", "07-04-2021", "08-04-2021", "09-04-2021", "12-04-2021", "13-04-2021", "14-04-2021", "15-04-2021", "16-04-2021", "19-04-2021", "20-04-2021", "21-04-2021", "22-04-2021", "23-04-2021", "26-04-2021", "27-04-2021", "28-04-2021", "29-04-2021", "30-04-2021" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        panelDaysWorking.setViewportView(listDaysWorking);

        btnAddPhysician.setText("Add Physician");
        btnAddPhysician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPhysicianActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAddPhysicianLayout = new javax.swing.GroupLayout(panelAddPhysician);
        panelAddPhysician.setLayout(panelAddPhysicianLayout);
        panelAddPhysicianLayout.setHorizontalGroup(
            panelAddPhysicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddPhysicianLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelAddPhysicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddPhysicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddPhysician, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(txtAddress)
                    .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtConsultation, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFullName))
                .addGap(18, 18, 18)
                .addGroup(panelAddPhysicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddPhysicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelExpertise)
                    .addComponent(panelDaysWorking))
                .addGap(67, 67, 67))
        );
        panelAddPhysicianLayout.setVerticalGroup(
            panelAddPhysicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddPhysicianLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelAddPhysicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddPhysicianLayout.createSequentialGroup()
                        .addGroup(panelAddPhysicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelAddPhysicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelAddPhysicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelExpertise, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAddPhysicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddPhysicianLayout.createSequentialGroup()
                        .addGroup(panelAddPhysicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtConsultation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelAddPhysicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddPhysician)
                            .addComponent(jButton3)))
                    .addGroup(panelAddPhysicianLayout.createSequentialGroup()
                        .addComponent(panelDaysWorking, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 80, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab2", panelAddPhysician);

        jLabel7.setText("Full Name");

        jLabel8.setText("Address");

        jLabel9.setText("Phone No.");

        btnAddPatient.setText("Add Patient");
        btnAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPatientActionPerformed(evt);
            }
        });

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAddPatientLayout = new javax.swing.GroupLayout(panelAddPatient);
        panelAddPatient.setLayout(panelAddPatientLayout);
        panelAddPatientLayout.setHorizontalGroup(
            panelAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddPatientLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAddPatientLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddPatient))
                    .addGroup(panelAddPatientLayout.createSequentialGroup()
                        .addGroup(panelAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddressPatient, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(txtPhonePatient, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFullNamePatient))))
                .addGap(218, 218, 218))
        );
        panelAddPatientLayout.setVerticalGroup(
            panelAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddPatientLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFullNamePatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtAddressPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPhonePatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panelAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPatient)
                    .addComponent(jButton4))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", panelAddPatient);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -33, -1, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPhysicianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPhysicianActionPerformed
        // TODO add your handling code here:
        if(validateFields("physician")){
            Physician newPhysician = new Physician();
            newPhysician.setFullName(txtFullName.getText());
            newPhysician.setAddress(txtAddress.getText());
            newPhysician.setPhoneNumber(Integer.parseInt(txtPhone.getText()));
            newPhysician.setExpertise((ArrayList<String>) listExpertise.getSelectedValuesList());
            for (int i=0;i<listDaysWorking.getSelectedIndices().length;i++){
                
                newPhysician.setSlots(listDaysWorking.getSelectedValuesList().get(i));
            }
            
            newPhysician.setConsultationHours(txtConsultation.getText());
            newPhysician.setWorkingDays((ArrayList<String>) listDaysWorking.getSelectedValuesList());
            newPhysician.setPhysicianId();
            Physician.setPhysicians(newPhysician);
        }
        else{
             Component frame = null;
        JOptionPane.showMessageDialog(frame,
    "Please fill the fields",
    "Invalid Data",
    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddPhysicianActionPerformed

    private void btnAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPatientActionPerformed
        // TODO add your handling code here:
         if(validateFields("patient")){
            Patient newPatient = new Patient();
            newPatient.setFullName(txtFullNamePatient.getText());
            newPatient.setAddress(txtAddressPatient.getText());
            newPatient.setPhoneNumber(Integer.parseInt(txtPhonePatient.getText()));
            newPatient.setPatientId();
            Patient.setPatients(newPatient);
        }
        else{
             Component frame = null;
        JOptionPane.showMessageDialog(frame,
    "Please fill the fields",
    "Invalid Data",
    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddPatientActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        jTabbedPane1.repaint();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Mainmenu newView = new Mainmenu();
        newView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPatient;
    private javax.swing.JButton btnAddPhysician;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listDaysWorking;
    private javax.swing.JList<String> listExpertise;
    private javax.swing.JPanel panelAddPatient;
    private javax.swing.JPanel panelAddPhysician;
    private javax.swing.JPanel panelAdmin;
    private javax.swing.JScrollPane panelDaysWorking;
    private javax.swing.JScrollPane panelExpertise;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAddressPatient;
    private javax.swing.JTextField txtConsultation;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtFullNamePatient;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPhonePatient;
    // End of variables declaration//GEN-END:variables

    private boolean validateFields(String personnel) {
        if(personnel.equals("physician")){
        return !(listExpertise.isSelectionEmpty() || listDaysWorking.isSelectionEmpty() || txtFullName.getText().equals("")|| "".equals(txtAddress.getText())|| "".equals(txtConsultation.getText())|| "".equals(txtPhone.getText()));
        }
        else if(personnel.equals("patient")){
        return !(txtFullNamePatient.getText().equals("") ||txtAddressPatient.getText().equals("")||txtPhonePatient.getText().equals("") ) ;
        }
        return false;
        }

}
