/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.util.ArrayList;
import physiotherapy.sports.injury.centre.psic.Patient;
import physiotherapy.sports.injury.centre.psic.Physician;
import physiotherapy.sports.injury.centre.psic.Room;
import physiotherapy.sports.injury.centre.psic.Treatment;

/**
 *
 * @author Mubeen Khan
 */
public class Mainmenu extends javax.swing.JFrame {

    /**
     * Creates new form Mainmenu
     */
    public Mainmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPatientMenu = new javax.swing.JButton();
        btnVisitorMenu = new javax.swing.JButton();
        btnPhysicianMenu = new javax.swing.JButton();
        btnAdminMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Physiotherapy Sports Injury Centre (PMIC)");
        setBackground(new java.awt.Color(204, 255, 204));
        setSize(new java.awt.Dimension(590, 420));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        btnPatientMenu.setText("Patient Login");
        btnPatientMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientMenuActionPerformed(evt);
            }
        });

        btnVisitorMenu.setText("Visitor Login");
        btnVisitorMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisitorMenuActionPerformed(evt);
            }
        });

        btnPhysicianMenu.setText("Physician Login");
        btnPhysicianMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhysicianMenuActionPerformed(evt);
            }
        });

        btnAdminMenu.setText("Admin Login");
        btnAdminMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminMenuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Main Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPhysicianMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdminMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPatientMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVisitorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnAdminMenu)
                .addGap(18, 18, 18)
                .addComponent(btnPhysicianMenu)
                .addGap(18, 18, 18)
                .addComponent(btnPatientMenu)
                .addGap(18, 18, 18)
                .addComponent(btnVisitorMenu)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPhysicianMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhysicianMenuActionPerformed
        // TODO add your handling code here:
        PhysicianView newView = new PhysicianView();
        newView.setVisible(true);
        setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_btnPhysicianMenuActionPerformed

    private void btnAdminMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminMenuActionPerformed
        // TODO add your handling code here:
        AdminView newView = new AdminView();
        newView.setVisible(true);
        setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnAdminMenuActionPerformed

    private void btnPatientMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientMenuActionPerformed
        // TODO add your handling code here:
        PatientView newView = new PatientView();
        newView.setVisible(true);
        setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnPatientMenuActionPerformed

    private void btnVisitorMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisitorMenuActionPerformed
        // TODO add your handling code here:
        VisitorView newView = new VisitorView();
        newView.setVisible(true);
        setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnVisitorMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //ArrayList To store Appointments
        ArrayList<Treatment> appointments = new ArrayList<Treatment>();

        //Hard coded Data
        ArrayList<Physician> physicians = addPhysicians(); //Add hardcoded physicians

        ArrayList<Patient> patients = addPatients();        //Add hardcoded patients

        addRooms();                  //Add hardcoded rooms

        addAppointments();   //Add hardcoded bookings
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainmenu().setVisible(true);
            }
        });
    }

    private static void addRooms() {
        Room room4 = new Room("medical consulting suite A");
        Room.setRooms(room4);
        Room room = new Room("medical consulting suite B");
        Room.setRooms(room);
        Room room1 = new Room("medical consulting suite C");
        Room.setRooms(room1);
        Room room2 = new Room("GYM");
        Room.setRooms(room2);
        Room room3 = new Room("Swimming Pool");
        Room.setRooms(room3);

    }

    //Method to add hard coded physycians
    private static ArrayList<Physician> addPhysicians() {
        ArrayList<Physician> physicians = new ArrayList<Physician>();
        

        Physician physician1 = new Physician();
        physician1.setFullName("Dr. Mubeen");
        physician1.setAddress("Dewsbury, UK");
        physician1.setPhoneNumber(55662233);
        physician1.setConsultationHours("05-04-2021 19:00:00");
        physician1.addExpertise("Rehabilitation");
        physician1.addExpertise("Osteopathy");
        physician1.setTimeTable("05-04-2021 09:00:00", "Rehabilitation");
        physician1.setTimeTable("05-04-2021 11:00:00", "Rehabilitation");
        physician1.setTimeTable("05-04-2021 13:00:00", "Rehabilitation");
        physician1.setTimeTable("05-04-2021 15:00:00", "Osteopathy");
        physician1.setTimeTable("05-04-2021 17:00:00", "Osteopathy");
        physician1.setTimeTable("06-04-2021 09:00:00", "Rehabilitation");
        physician1.setTimeTable("06-04-2021 11:00:00", "Rehabilitation");
        physician1.setTimeTable("06-04-2021 13:00:00", "Rehabilitation");
        physician1.setTimeTable("06-04-2021 15:00:00", "Osteopathy");
        physician1.setTimeTable("06-04-2021 17:00:00", "Osteopathy");
        physician1.setTimeTable("12-04-2021 09:00:00", "Rehabilitation");
        physician1.setTimeTable("12-04-2021 11:00:00", "Rehabilitation");
        physician1.setTimeTable("12-04-2021 13:00:00", "Osteopathy");
        physician1.setTimeTable("12-04-2021 15:00:00", "Osteopathy");
        physician1.setTimeTable("12-04-2021 17:00:00", "Osteopathy");
        physician1.setTimeTable("13-04-2021 09:00:00", "Osteopathy");
        physician1.setTimeTable("13-04-2021 11:00:00", "Osteopathy");
        physician1.setTimeTable("13-04-2021 13:00:00", "Rehabilitation");
        physician1.setTimeTable("13-04-2021 15:00:00", "Rehabilitation");
        physician1.setTimeTable("13-04-2021 17:00:00", "Rehabilitation");
        physician1.setTimeTable("19-04-2021 09:00:00", "Rehabilitation");
        physician1.setTimeTable("19-04-2021 11:00:00", "Rehabilitation");
        physician1.setTimeTable("19-04-2021 13:00:00", "Osteopathy");
        physician1.setTimeTable("19-04-2021 15:00:00", "Osteopathy");
        physician1.setTimeTable("19-04-2021 17:00:00", "Osteopathy");
        physician1.setTimeTable("20-04-2021 09:00:00", "Rehabilitation");
        physician1.setTimeTable("20-04-2021 11:00:00", "Rehabilitation");
        physician1.setTimeTable("20-04-2021 13:00:00", "Osteopathy");
        physician1.setTimeTable("20-04-2021 15:00:00", "Osteopathy");
        physician1.setTimeTable("20-04-2021 17:00:00", "Osteopathy");
        physician1.setTimeTable("26-04-2021 09:00:00", "Osteopathy");
        physician1.setTimeTable("26-04-2021 11:00:00", "Osteopathy");
        physician1.setTimeTable("26-04-2021 13:00:00", "Osteopathy");
        physician1.setTimeTable("26-04-2021 15:00:00", "Rehabilitation");
        physician1.setTimeTable("26-04-2021 17:00:00", "Rehabilitation");
        physician1.setTimeTable("27-04-2021 09:00:00", "Osteopathy");
        physician1.setTimeTable("27-04-2021 11:00:00", "Osteopathy");
        physician1.setTimeTable("27-04-2021 13:00:00", "Osteopathy");
        physician1.setTimeTable("27-04-2021 15:00:00", "Osteopathy");
        physician1.setTimeTable("27-04-2021 17:00:00", "Osteopathy");
        physician1.setPhysicianId();
        Physician.setPhysicians(physician1);

        Physician physician2 = new Physician();
        physician2.setFullName("Dr. ALI");
        physician2.setAddress("Bradford, UK");
        physician2.setPhoneNumber(32435466);
        physician2.setConsultationHours("07-04-2021 07:00:00");
        physician2.addExpertise("Rehabilitation");
        physician2.addExpertise("Osteopathy");
        physician2.setTimeTable("06-04-2021 09:00:00", "Rehabilitation");
        physician2.setTimeTable("06-04-2021 11:00:00", "Rehabilitation");
        physician2.setTimeTable("06-04-2021 13:00:00", "Rehabilitation");
        physician2.setTimeTable("06-04-2021 15:00:00", "Osteopathy");
        physician2.setTimeTable("06-04-2021 17:00:00", "Osteopathy");
        physician2.setTimeTable("07-04-2021 09:00:00", "Rehabilitation");
        physician2.setTimeTable("07-04-2021 11:00:00", "Rehabilitation");
        physician2.setTimeTable("07-04-2021 13:00:00", "Rehabilitation");
        physician2.setTimeTable("07-04-2021 15:00:00", "Osteopathy");
        physician2.setTimeTable("07-04-2021 17:00:00", "Osteopathy");
        physician2.setTimeTable("08-04-2021 09:00:00", "Rehabilitation");
        physician2.setTimeTable("08-04-2021 11:00:00", "Rehabilitation");
        physician2.setTimeTable("08-04-2021 13:00:00", "Osteopathy");
        physician2.setTimeTable("08-04-2021 15:00:00", "Osteopathy");
        physician2.setTimeTable("08-04-2021 17:00:00", "Osteopathy");
        physician2.setTimeTable("13-04-2021 09:00:00", "Osteopathy");
        physician2.setTimeTable("13-04-2021 11:00:00", "Osteopathy");
        physician2.setTimeTable("13-04-2021 13:00:00", "Rehabilitation");
        physician2.setTimeTable("13-04-2021 15:00:00", "Rehabilitation");
        physician2.setTimeTable("13-04-2021 17:00:00", "Rehabilitation");
        physician2.setTimeTable("14-04-2021 09:00:00", "Rehabilitation");
        physician2.setTimeTable("14-04-2021 11:00:00", "Rehabilitation");
        physician2.setTimeTable("14-04-2021 13:00:00", "Osteopathy");
        physician2.setTimeTable("14-04-2021 15:00:00", "Osteopathy");
        physician2.setTimeTable("14-04-2021 17:00:00", "Osteopathy");
        physician2.setTimeTable("15-04-2021 09:00:00", "Rehabilitation");
        physician2.setTimeTable("15-04-2021 11:00:00", "Rehabilitation");
        physician2.setTimeTable("15-04-2021 13:00:00", "Osteopathy");
        physician2.setTimeTable("15-04-2021 15:00:00", "Osteopathy");
        physician2.setTimeTable("15-04-2021 17:00:00", "Osteopathy");
        physician2.setTimeTable("20-04-2021 09:00:00", "Rehabilitation");
        physician2.setTimeTable("20-04-2021 11:00:00", "Rehabilitation");
        physician2.setTimeTable("20-04-2021 13:00:00", "Osteopathy");
        physician2.setTimeTable("20-04-2021 15:00:00", "Osteopathy");
        physician2.setTimeTable("20-04-2021 17:00:00", "Osteopathy");
        physician2.setTimeTable("21-04-2021 09:00:00", "Rehabilitation");
        physician2.setTimeTable("21-04-2021 11:00:00", "Rehabilitation");
        physician2.setTimeTable("21-04-2021 13:00:00", "Osteopathy");
        physician2.setTimeTable("21-04-2021 15:00:00", "Osteopathy");
        physician2.setTimeTable("21-04-2021 17:00:00", "Osteopathy");
        physician2.setTimeTable("22-04-2021 09:00:00", "Rehabilitation");
        physician2.setTimeTable("22-04-2021 11:00:00", "Rehabilitation");
        physician2.setTimeTable("22-04-2021 13:00:00", "Osteopathy");
        physician2.setTimeTable("22-04-2021 15:00:00", "Osteopathy");
        physician2.setTimeTable("22-04-2021 17:00:00", "Osteopathy");
        physician2.setTimeTable("27-04-2021 09:00:00", "Osteopathy");
        physician2.setTimeTable("27-04-2021 11:00:00", "Osteopathy");
        physician2.setTimeTable("27-04-2021 13:00:00", "Osteopathy");
        physician2.setTimeTable("27-04-2021 15:00:00", "Rehabilitation");
        physician2.setTimeTable("27-04-2021 17:00:00", "Rehabilitation");
        physician2.setTimeTable("28-04-2021 09:00:00", "Osteopathy");
        physician2.setTimeTable("28-04-2021 11:00:00", "Osteopathy");
        physician2.setTimeTable("28-04-2021 13:00:00", "Osteopathy");
        physician2.setTimeTable("28-04-2021 15:00:00", "Osteopathy");
        physician2.setTimeTable("28-04-2021 17:00:00", "Osteopathy");
        physician2.setTimeTable("29-04-2021 09:00:00", "Rehabilitation");
        physician2.setTimeTable("29-04-2021 11:00:00", "Rehabilitation");
        physician2.setTimeTable("29-04-2021 13:00:00", "Rehabilitation");
        physician2.setTimeTable("29-04-2021 15:00:00", "Rehabilitation");
        physician2.setTimeTable("29-04-2021 17:00:00", "Rehabilitation");
        physician2.setPhysicianId();
        Physician.setPhysicians(physician2);

        Physician physician3 = new Physician();
        physician3.setFullName("Dr. Isaac");
        physician3.setAddress("London, UK");
        physician3.setPhoneNumber(44556688);
        physician3.setConsultationHours("09-04-2021 19:00:00");
        physician3.addExpertise("Physiotherapy");
        physician3.setTimeTable("08-04-2021 09:00:00", "Physiotherapy");
        physician3.setTimeTable("08-04-2021 11:00:00", "Physiotherapy");
        physician3.setTimeTable("08-04-2021 13:00:00", "Physiotherapy");
        physician3.setTimeTable("08-04-2021 15:00:00", "Physiotherapy");
        physician3.setTimeTable("08-04-2021 17:00:00", "Physiotherapy");
        physician3.setTimeTable("09-04-2021 09:00:00", "Physiotherapy");
        physician3.setTimeTable("09-04-2021 11:00:00", "Physiotherapy");
        physician3.setTimeTable("09-04-2021 13:00:00", "Physiotherapy");
        physician3.setTimeTable("09-04-2021 15:00:00", "Physiotherapy");
        physician3.setTimeTable("09-04-2021 17:00:00", "Physiotherapy");
        physician3.setTimeTable("10-04-2021 09:00:00", "Physiotherapy");
        physician3.setTimeTable("10-04-2021 11:00:00", "Physiotherapy");
        physician3.setTimeTable("10-04-2021 13:00:00", "Physiotherapy");
        physician3.setTimeTable("10-04-2021 15:00:00", "Physiotherapy");
        physician3.setTimeTable("10-04-2021 17:00:00", "Physiotherapy");
        physician3.setTimeTable("15-04-2021 09:00:00", "Physiotherapy");
        physician3.setTimeTable("15-04-2021 11:00:00", "Physiotherapy");
        physician3.setTimeTable("15-04-2021 13:00:00", "Physiotherapy");
        physician3.setTimeTable("15-04-2021 15:00:00", "Physiotherapy");
        physician3.setTimeTable("15-04-2021 17:00:00", "Physiotherapy");
        physician3.setTimeTable("16-04-2021 09:00:00", "Physiotherapy");
        physician3.setTimeTable("16-04-2021 11:00:00", "Physiotherapy");
        physician3.setTimeTable("16-04-2021 13:00:00", "Physiotherapy");
        physician3.setTimeTable("16-04-2021 15:00:00", "Physiotherapy");
        physician3.setTimeTable("16-04-2021 17:00:00", "Physiotherapy");
        physician3.setTimeTable("17-04-2021 09:00:00", "Physiotherapy");
        physician3.setTimeTable("17-04-2021 11:00:00", "Physiotherapy");
        physician3.setTimeTable("17-04-2021 13:00:00", "Physiotherapy");
        physician3.setTimeTable("17-04-2021 15:00:00", "Physiotherapy");
        physician3.setTimeTable("17-04-2021 17:00:00", "Physiotherapy");
        physician3.setTimeTable("22-04-2021 09:00:00", "Physiotherapy");
        physician3.setTimeTable("22-04-2021 11:00:00", "Physiotherapy");
        physician3.setTimeTable("22-04-2021 13:00:00", "Physiotherapy");
        physician3.setTimeTable("22-04-2021 15:00:00", "Physiotherapy");
        physician3.setTimeTable("22-04-2021 17:00:00", "Physiotherapy");
        physician3.setTimeTable("23-04-2021 09:00:00", "Physiotherapy");
        physician3.setTimeTable("23-04-2021 11:00:00", "Physiotherapy");
        physician3.setTimeTable("23-04-2021 13:00:00", "Physiotherapy");
        physician3.setTimeTable("23-04-2021 15:00:00", "Physiotherapy");
        physician3.setTimeTable("23-04-2021 17:00:00", "Physiotherapy");
        physician3.setTimeTable("24-04-2021 09:00:00", "Physiotherapy");
        physician3.setTimeTable("24-04-2021 11:00:00", "Physiotherapy");
        physician3.setTimeTable("24-04-2021 13:00:00", "Physiotherapy");
        physician3.setTimeTable("24-04-2021 15:00:00", "Physiotherapy");
        physician3.setTimeTable("24-04-2021 17:00:00", "Physiotherapy");
        physician3.setTimeTable("29-04-2021 09:00:00", "Physiotherapy");
        physician3.setTimeTable("29-04-2021 11:00:00", "Physiotherapy");
        physician3.setTimeTable("29-04-2021 13:00:00", "Physiotherapy");
        physician3.setTimeTable("29-04-2021 15:00:00", "Physiotherapy");
        physician3.setTimeTable("29-04-2021 17:00:00", "Physiotherapy");
        physician3.setTimeTable("30-04-2021 09:00:00", "Physiotherapy");
        physician3.setTimeTable("30-04-2021 11:00:00", "Physiotherapy");
        physician3.setTimeTable("30-04-2021 13:00:00", "Physiotherapy");
        physician3.setTimeTable("30-04-2021 15:00:00", "Physiotherapy");
        physician3.setTimeTable("30-04-2021 17:00:00", "Physiotherapy");
        physician3.setTimeTable("01-05-2021 09:00:00", "Physiotherapy");
        physician3.setTimeTable("02-05-2021 11:00:00", "Physiotherapy");
        physician3.setTimeTable("03-05-2021 13:00:00", "Physiotherapy");
        physician3.setTimeTable("04-05-2021 15:00:00", "Physiotherapy");
        physician3.setTimeTable("04-05-2021 17:00:00", "Physiotherapy");
        physician3.setPhysicianId();
        Physician.setPhysicians(physician3);
        
        Physician physician4 = new Physician();
        physician4.setFullName("Dr. Sadiq");
        physician4.setAddress("Halifax, UK");
        physician4.setPhoneNumber(45356457);
        physician4.setConsultationHours("09-04-2021 19:00:00");
        physician4.addExpertise("Physiotherapy");
        physician4.addExpertise("Rehabilitation");
        physician4.addExpertise("Osteopathy");
        physician4.setTimeTable("08-04-2021 09:00:00", "Physiotherapy");
        physician4.setTimeTable("08-04-2021 11:00:00", "Physiotherapy");
        physician4.setTimeTable("08-04-2021 13:00:00", "Rehabilitation");
        physician4.setTimeTable("08-04-2021 15:00:00", "Rehabilitation");
        physician4.setTimeTable("08-04-2021 17:00:00", "Physiotherapy");
        physician4.setTimeTable("09-04-2021 09:00:00", "Physiotherapy");
        physician4.setTimeTable("09-04-2021 11:00:00", "Physiotherapy");
        physician4.setTimeTable("09-04-2021 13:00:00", "Physiotherapy");
        physician4.setTimeTable("09-04-2021 15:00:00", "Physiotherapy");
        physician4.setTimeTable("09-04-2021 17:00:00", "Physiotherapy");
        physician4.setTimeTable("10-04-2021 09:00:00", "Osteopathy");
        physician4.setTimeTable("10-04-2021 11:00:00", "Osteopathy");
        physician4.setTimeTable("10-04-2021 13:00:00", "Osteopathy");
        physician4.setTimeTable("10-04-2021 15:00:00", "Osteopathy");
        physician4.setTimeTable("10-04-2021 17:00:00", "Osteopathy");
        physician4.setTimeTable("15-04-2021 09:00:00", "Physiotherapy");
        physician4.setTimeTable("15-04-2021 11:00:00", "Physiotherapy");
        physician4.setTimeTable("15-04-2021 13:00:00", "Physiotherapy");
        physician4.setTimeTable("15-04-2021 15:00:00", "Physiotherapy");
        physician4.setTimeTable("15-04-2021 17:00:00", "Physiotherapy");
        physician4.setTimeTable("16-04-2021 09:00:00", "Rehabilitation");
        physician4.setTimeTable("16-04-2021 11:00:00", "Rehabilitation");
        physician4.setTimeTable("16-04-2021 13:00:00", "Rehabilitation");
        physician4.setTimeTable("16-04-2021 15:00:00", "Rehabilitation");
        physician4.setTimeTable("16-04-2021 17:00:00", "Rehabilitation");
        physician4.setTimeTable("17-04-2021 09:00:00", "Osteopathy");
        physician4.setTimeTable("17-04-2021 11:00:00", "Osteopathy");
        physician4.setTimeTable("17-04-2021 13:00:00", "Osteopathy");
        physician4.setTimeTable("17-04-2021 15:00:00", "Osteopathy");
        physician4.setTimeTable("17-04-2021 17:00:00", "Osteopathy");
        physician4.setTimeTable("22-04-2021 09:00:00", "Physiotherapy");
        physician4.setTimeTable("22-04-2021 11:00:00", "Physiotherapy");
        physician4.setTimeTable("22-04-2021 13:00:00", "Physiotherapy");
        physician4.setTimeTable("22-04-2021 15:00:00", "Physiotherapy");
        physician4.setTimeTable("22-04-2021 17:00:00", "Physiotherapy");
        physician4.setTimeTable("23-04-2021 09:00:00", "Osteopathy");
        physician4.setTimeTable("23-04-2021 11:00:00", "Osteopathy");
        physician4.setTimeTable("23-04-2021 13:00:00", "Osteopathy");
        physician4.setTimeTable("23-04-2021 15:00:00", "Osteopathy");
        physician4.setTimeTable("23-04-2021 17:00:00", "Osteopathy");
        physician4.setTimeTable("24-04-2021 09:00:00", "Rehabilitation");
        physician4.setTimeTable("24-04-2021 11:00:00", "Rehabilitation");
        physician4.setTimeTable("24-04-2021 13:00:00", "Rehabilitation");
        physician4.setTimeTable("24-04-2021 15:00:00", "Rehabilitation");
        physician4.setTimeTable("24-04-2021 17:00:00", "Rehabilitation");
        physician4.setTimeTable("29-04-2021 09:00:00", "Osteopathy");
        physician4.setTimeTable("29-04-2021 11:00:00", "Osteopathy");
        physician4.setTimeTable("29-04-2021 13:00:00", "Osteopathy");
        physician4.setTimeTable("29-04-2021 15:00:00", "Osteopathy");
        physician4.setTimeTable("29-04-2021 17:00:00", "Osteopathy");
        physician4.setTimeTable("30-04-2021 09:00:00", "Rehabilitation");
        physician4.setTimeTable("30-04-2021 11:00:00", "Rehabilitation");
        physician4.setTimeTable("30-04-2021 13:00:00", "Rehabilitation");
        physician4.setTimeTable("30-04-2021 15:00:00", "Rehabilitation");
        physician4.setTimeTable("30-04-2021 17:00:00", "Rehabilitation");
        physician4.setTimeTable("01-05-2021 09:00:00", "Physiotherapy");
        physician4.setTimeTable("02-05-2021 11:00:00", "Physiotherapy");
        physician4.setTimeTable("03-05-2021 13:00:00", "Physiotherapy");
        physician4.setTimeTable("04-05-2021 15:00:00", "Physiotherapy");
        physician4.setTimeTable("04-05-2021 17:00:00", "Physiotherapy");
        physician4.setPhysicianId();
        Physician.setPhysicians(physician4);

        return physicians;
    }

    private static ArrayList<Patient> addPatients() {
        ArrayList<Patient> patients = new ArrayList<Patient>();
        Patient patient1 = new Patient();
        patient1.setFullName("David");
        patient1.setAddress("19 Calver Avenue");
        patient1.setPhoneNumber(11223344);
        patient1.setPatientId();
        Patient.setPatients(patient1);

        Patient patient2 = new Patient();
        patient2.setFullName("Babar");
        patient2.setAddress("49 Gleanings Avenue");
        patient2.setPhoneNumber(22334455);
        patient2.setPatientId();
        Patient.setPatients(patient2);

        Patient patient3 = new Patient();
        patient3.setFullName("Ahmed");
        patient3.setAddress("14 Raglan Terrace");
        patient3.setPhoneNumber(22334466);
        patient3.setPatientId();
        Patient.setPatients(patient3);

        Patient patient4 = new Patient();
        patient4.setFullName("Jonas");
        patient4.setAddress("53 St Stephen Rd");
        patient4.setPhoneNumber(66778899);
        patient4.setPatientId();
        Patient.setPatients(patient4);
        
        Patient patient5 = new Patient();
        patient5.setFullName("Elise");
        patient5.setAddress("15 Gleanings Avenue");
        patient5.setPhoneNumber(22334455);
        patient5.setPatientId();
        Patient.setPatients(patient5);
        
        Patient patient6 = new Patient();
        patient6.setFullName("Ayesha");
        patient6.setAddress("25 Raglan Terrace");
        patient6.setPhoneNumber(22233344);
        patient6.setPatientId();
        Patient.setPatients(patient6);
        
        Patient patient7 = new Patient();
        patient7.setFullName("Sonya");
        patient7.setAddress("30 Calver Avenue");
        patient7.setPhoneNumber(12343212);
        patient7.setPatientId();
        Patient.setPatients(patient7);
        
        Patient patient8 = new Patient();
        patient8.setFullName("Christy");
        patient8.setAddress("33 Sun bridge Rd");
        patient8.setPhoneNumber(33577226);
        patient8.setPatientId();
        Patient.setPatients(patient8);
        
        Patient patient9 = new Patient();
        patient9.setFullName("Lisa");
        patient9.setAddress("12 St Stephens Rd");
        patient9.setPhoneNumber(22556677);
        patient9.setPatientId();
        Patient.setPatients(patient9);
        
        Patient patient10 = new Patient();
        patient10.setFullName("Shaun");
        patient10.setAddress("25 Gleanings Avenue");
        patient10.setPhoneNumber(17895642);
        patient10.setPatientId();
        Patient.setPatients(patient10);

        return patients;
    }
    private static void addAppointments(){
    Treatment newTreatment = new Treatment("Rehabilitation","Tue 06-04-2021 09:00:00","Dr. ALI", "David","GYM");
        Treatment newTreatment1 = new Treatment("Osteopathy","Mon 05-04-2021 15:00:00","Dr. Mubeen", "Babar","GYM");
Treatment newTreatment2 = new Treatment("Physiotherapy","Thu 08-04-2021 11:00:00","Dr. Isaac", "Ahmed","GYM");
        Treatment newTreatment3 = new Treatment("Osteopathy","Mon 12-04-2021 17:00:00","Dr. Mubeen", "Jonas","GYM");
        Treatment newTreatment4 = new Treatment("Osteopathy","08-04-2021 15:00:00","Dr. ALI", "Elise","GYM");
        Treatment newTreatment5 = new Treatment("Rehabilitation","Mon 05-04-2021 09:00:00","Dr. Mubeen", "Ayesha","GYM");
        Treatment newTreatment6 = new Treatment("Physiotherapy","Sat 17-04-2021 13:00:00","Dr. Isaac", "Lisa","GYM");
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminMenu;
    private javax.swing.JButton btnPatientMenu;
    private javax.swing.JButton btnPhysicianMenu;
    private javax.swing.JButton btnVisitorMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
